image: conoria/manjaro-base

pages:
  script:
  - chown -R maker:users .
  - release=$(grep "pkgver=" PKGBUILD | sed 's/pkgver=//g')
  - /usr/local/sbin/pkg.sh
  - sed -i 's/CARCH="x86_64"/CARCH="i686"/g' /etc/makepkg.conf
  - sudo -u maker makepkg --repackage
  - cd src/wire-desktop-release-$release/wrap/build/
  - tar -cvzf Wire-linux-x64-$release.tgz ./Wire-linux-x64
  - tar -cvzf Wire-linux-ia32-$release.tgz  ./Wire-linux-ia32
  - cd ../../../../
  - mkdir public
  - mv src/wire-desktop-release-$release/wrap/build/*.tgz public
  - mv *.pkg.tar.xz public
  - curl -o index.sh https://gitlab.com/snippets/27473/raw
  - chmod +x index.sh
  - sed -i -e 's/\r$//' index.sh
  - cd public
  - ../index.sh https://conoria.gitlab.io/wire-pkgbuilds > index.html
  
  artifacts:
    paths:
    - public
    
  only:
  - master
