image: conoria/manjaro-base
pages:
  script:
  - chown -R maker:users .
  - /usr/local/sbin/pkg.sh
  - sed -i 's/CARCH="x86_64"/CARCH="i686"/g' /etc/makepkg.conf
  - sudo -u maker makepkg --repackage
  - mkdir -p public/_includes
  - mv *.pkg.tar.xz public
  - curl -o index.sh https://gitlab.com/snippets/27473/raw
  - chmod +x index.sh
  - sed -i -e 's/\r$//' index.sh
  - cd public
  - ../index.sh https://conoria.gitlab.io/wire-pkgbuilds > index.html
  
  artifacts:
    paths:
    - public
    
  only:
  - master